name: cafenorte
version: "1.0.0"
config-version: 2
profile: cafenorte
model-paths: [models]
test-paths: [tests]
target-path: target
clean-targets: [target, dbt_packages]

models:
  cafenorte:
    staging:
      +schema: staging
      +materialized: view
    intermediate:
      +schema: intermediate
      +materialized: table
    marts:
      +schema: analytics
      +materialized: table

vars:
  anchor_date: "'2026-03-31'"
