import os

SECRET_KEY = os.environ["SUPERSET_SECRET_KEY"]
SQLALCHEMY_DATABASE_URI = os.environ["SUPERSET_META_DB"]
REDIS_HOST = "redis"
REDIS_PORT = 6379
RESULTS_BACKEND = None
CACHE_CONFIG = {
    "CACHE_TYPE": "RedisCache",
    "CACHE_DEFAULT_TIMEOUT": 300,
    "CACHE_KEY_PREFIX": "cafenorte_",
    "CACHE_REDIS_URL": os.environ["REDIS_URL"],
}
DATA_CACHE_CONFIG = CACHE_CONFIG
SQLLAB_CTAS_NO_LIMIT = True
FEATURE_FLAGS = {
    "DASHBOARD_NATIVE_FILTERS": True,
    "DASHBOARD_RBAC": True,
}
